version: "3.8"

services:
  # Dịch vụ MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: warehouse
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  # Dịch vụ Backend (Spring Boot)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=warehouse
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network

  # Dịch vụ Frontend (React + Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

# Định nghĩa volume để lưu dữ liệu MySQL
volumes:
  mysql-data:

# Định nghĩa network để các dịch vụ giao tiếp với nhau
networks:
  app-network:
    driver: bridge
